analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.1550244563259184
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.8576229636091739
  brandStrength: 0.4088468113914132
  rhythmicContrast: 0.295846791472286
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  lightness: 0.004365523112937808
purpose: []
favicon: null
name: psvensson
typography_spectrum: 0.7103701799642295
